name: firebase_crud_example
description: An example to show crud operations in firebase

#  Flutter 2.0.0 • channel stable • https://github.com/flutter/flutter.git
#  Framework • revision 60bd88df91 (25 hours ago) • 2021-03-03 09:13:17 -0800
#  Engine • revision 40441def69
#  Tools • Dart 2.12.0


version: 1.0.12

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  google_sign_in: ^5.0.1
  firebase_core: ^1.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  visibility_detector: ^0.2.0-nullsafety.1
  cupertino_icons: ^1.0.1
  firebase: ^9.0.0
  firebase_auth: ^1.0.1
  #only mobile
  #cloud_firestore: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: ^1.0.2+2

flutter:

  uses-material-design: true
  assets:
    - assets/images/